export const songSeedData = [
  {
    title: "A small miracle",
    src: "a-small-miracle-132333.mp3",
    thumbnailSrc: "thumbnail_00001.png",
    viewCount: 0,
  },
  {
    title: "Abstract fashion pop",
    src: "abstract-fashion-pop-131283.mp3",
    thumbnailSrc: "thumbnail_00002.png",
    viewCount: 0,
  },
  {
    title: "After party",
    src: "after-party-144155.mp3",
    thumbnailSrc: "thumbnail_00003.png",
    viewCount: 0,
  },
  {
    title: "Arabic music",
    src: "arabic-music-141627.mp3",
    thumbnailSrc: "thumbnail_00004.png",
    viewCount: 0,
  },
  {
    title: "Awaken",
    src: "awaken-136824.mp3",
    thumbnailSrc: "thumbnail_00005.png",
    viewCount: 0,
  },
  {
    title: "Beautiful ambient corporate inspiration",
    src: "beautiful-ambient-corporate-inspiration-143546.mp3",
    thumbnailSrc: "thumbnail_00006.png",
    viewCount: 0,
  },
  {
    title: "Beautiful trip",
    src: "beautiful-trip-142481.mp3",
    thumbnailSrc: "thumbnail_00007.png",
    viewCount: 0,
  },
  {
    title: "Best moment",
    src: "best-moment-142894.mp3",
    thumbnailSrc: "thumbnail_00008.png",
    viewCount: 0,
  },
  {
    title: "Beyond equations",
    src: "beyond-equations-141460.mp3",
    thumbnailSrc: "thumbnail_00009.png",
    viewCount: 0,
  },
  {
    title: "Bookmark in a book",
    src: "bookmark-in-a-book-140930.mp3",
    thumbnailSrc: "thumbnail_00010.png",
    viewCount: 0,
  },
  {
    title: "Bright positive corporate technology",
    src: "bright-positive-corporate-technology-143545.mp3",
    thumbnailSrc: "thumbnail_00011.png",
    viewCount: 0,
  },
  {
    title: "Christian piano music",
    src: "christian-piano-music-143489.mp3",
    thumbnailSrc: "thumbnail_00012.png",
    viewCount: 0,
  },
  {
    title: "Cinematic mood",
    src: "cinematic-mood-141761.mp3",
    thumbnailSrc: "thumbnail_00013.png",
    viewCount: 0,
  },
  {
    title: "Coniferous forest",
    src: "coniferous-forest-142569.mp3",
    thumbnailSrc: "thumbnail_00014.png",
    viewCount: 0,
  },
  {
    title: "Corporate rhythm",
    src: "corporate-rhythm-140895.mp3",
    thumbnailSrc: "thumbnail_00015.png",
    viewCount: 0,
  },
  {
    title: "Dark mystery trailer taking our time",
    src: "dark-mystery-trailer-taking-our-time-131566.mp3",
    thumbnailSrc: "thumbnail_00016.png",
    viewCount: 0,
  },
  {
    title: "Drop it",
    src: "drop-it-124014.mp3",
    thumbnailSrc: "thumbnail_00017.png",
    viewCount: 0,
  },
  {
    title: "Easy lifestyle 137766 ",
    src: "easy-lifestyle-137766 (1).mp3",
    thumbnailSrc: "thumbnail_00018.png",
    viewCount: 0,
  },
  {
    title: "Easy lifestyle",
    src: "easy-lifestyle-137766.mp3",
    thumbnailSrc: "thumbnail_00019.png",
    viewCount: 0,
  },
  {
    title: "Electro summer positive party",
    src: "electro-summer-positive-party-141081.mp3",
    thumbnailSrc: "thumbnail_00020.png",
    viewCount: 0,
  },
  {
    title: "Emotional piano",
    src: "emotional-piano-141472.mp3",
    thumbnailSrc: "thumbnail_00021.png",
    viewCount: 0,
  },
  {
    title: "Emotional thoughtful piano",
    src: "emotional-thoughtful-piano-141580.mp3",
    thumbnailSrc: "thumbnail_00022.png",
    viewCount: 0,
  },
  {
    title: "Energetic rock trailer",
    src: "energetic-rock-trailer-140906.mp3",
    thumbnailSrc: "thumbnail_00023.png",
    viewCount: 0,
  },
  {
    title: "Epic cinematic heroic motivational rise trailer",
    src: "epic-cinematic-heroic-motivational-rise-trailer-141042.mp3",
    thumbnailSrc: "thumbnail_00024.png",
    viewCount: 0,
  },
  {
    title: "Epic dance",
    src: "epic-dance-141200.mp3",
    thumbnailSrc: "thumbnail_00025.png",
    viewCount: 0,
  },
  {
    title: "Epic relaxing flute music",
    src: "epic-relaxing-flute-music-144009.mp3",
    thumbnailSrc: "thumbnail_00026.png",
    viewCount: 0,
  },
  {
    title: "Escape",
    src: "escape-143112.mp3",
    thumbnailSrc: "thumbnail_00027.png",
    viewCount: 0,
  },
  {
    title: "Fight",
    src: "fight-142564.mp3",
    thumbnailSrc: "thumbnail_00028.png",
    viewCount: 0,
  },
  {
    title: "First steps",
    src: "first-steps-141242.mp3",
    thumbnailSrc: "thumbnail_00029.png",
    viewCount: 0,
  },
  {
    title: "Floating abstract",
    src: "floating-abstract-142819.mp3",
    thumbnailSrc: "thumbnail_00030.png",
    viewCount: 0,
  },
  {
    title: "Good morning life",
    src: "good-morning-life-142546.mp3",
    thumbnailSrc: "thumbnail_00031.png",
    viewCount: 0,
  },
  {
    title: "Happy uplifting acoustic guitar background music",
    src: "happy-uplifting-acoustic-guitar-background-music-143199.mp3",
    thumbnailSrc: "thumbnail_00032.png",
    viewCount: 0,
  },
  {
    title: "I will be here vocal edm",
    src: "i-will-be-here-vocal-edm-140857.mp3",
    thumbnailSrc: "thumbnail_00033.png",
    viewCount: 0,
  },
  {
    title: "In a magical forest",
    src: "in-a-magical-forest-144306.mp3",
    thumbnailSrc: "thumbnail_00034.png",
    viewCount: 0,
  },
  {
    title: "Indie summer",
    src: "indie-summer-141351.mp3",
    thumbnailSrc: "thumbnail_00035.png",
    viewCount: 0,
  },
  {
    title: "Inspire tomorrow",
    src: "inspire-tomorrow-140918.mp3",
    thumbnailSrc: "thumbnail_00036.png",
    viewCount: 0,
  },
  {
    title: "Inspiring cinematic ambient",
    src: "inspiring-cinematic-ambient-116199.mp3",
    thumbnailSrc: "thumbnail_00037.png",
    viewCount: 0,
  },
  {
    title: "Inspiring morning",
    src: "inspiring-morning-141806.mp3",
    thumbnailSrc: "thumbnail_00038.png",
    viewCount: 0,
  },
  {
    title: "Interstellar space travel",
    src: "interstellar-space-travel-141121.mp3",
    thumbnailSrc: "thumbnail_00039.png",
    viewCount: 0,
  },
  {
    title: "Lifelike",
    src: "lifelike-126735.mp3",
    thumbnailSrc: "thumbnail_00040.png",
    viewCount: 0,
  },
  {
    title: "Lofi beat",
    src: "lofi-beat-140856.mp3",
    thumbnailSrc: "thumbnail_00041.png",
    viewCount: 0,
  },
  {
    title: "Lofi vintage",
    src: "lofi-vintage-140859.mp3",
    thumbnailSrc: "thumbnail_00042.png",
    viewCount: 0,
  },
  {
    title: "Love mellow piano",
    src: "love-mellow-piano-143300.mp3",
    thumbnailSrc: "thumbnail_00043.png",
    viewCount: 0,
  },
  {
    title: "Meditation relaxing and chill",
    src: "meditation-relaxing-and-chill-143219.mp3",
    thumbnailSrc: "thumbnail_00044.png",
    viewCount: 0,
  },
  {
    title: "Modern vlog",
    src: "modern-vlog-140795.mp3",
    thumbnailSrc: "thumbnail_00045.png",
    viewCount: 0,
  },
  {
    title: "Mountain path",
    src: "mountain-path-125573.mp3",
    thumbnailSrc: "thumbnail_00046.png",
    viewCount: 0,
  },
  {
    title: "My time",
    src: "my-time-143975.mp3",
    thumbnailSrc: "thumbnail_00047.png",
    viewCount: 0,
  },
  {
    title: "News time",
    src: "news-time-141357.mp3",
    thumbnailSrc: "thumbnail_00048.png",
    viewCount: 0,
  },
  {
    title: "Password infinity",
    src: "password-infinity-123276.mp3",
    thumbnailSrc: "thumbnail_00049.png",
    viewCount: 0,
  },
  {
    title: "Please calm my mind",
    src: "please-calm-my-mind-125566.mp3",
    thumbnailSrc: "thumbnail_00050.png",
    viewCount: 0,
  },
  {
    title: "Pop rock motivational",
    src: "pop-rock-motivational-141952.mp3",
    thumbnailSrc: "thumbnail_00051.png",
    viewCount: 0,
  },
  {
    title: "Relaxed vlog night street",
    src: "relaxed-vlog-night-street-131746.mp3",
    thumbnailSrc: "thumbnail_00052.png",
    viewCount: 0,
  },
  {
    title: "Relaxing music with flute",
    src: "relaxing-music-with-flute-144016.mp3",
    thumbnailSrc: "thumbnail_00053.png",
    viewCount: 0,
  },
  {
    title: "Risk",
    src: "risk-136788.mp3",
    thumbnailSrc: "thumbnail_00054.png",
    viewCount: 0,
  },
  {
    title: "Rocket phonk music",
    src: "rocket-phonk-music-141359.mp3",
    thumbnailSrc: "thumbnail_00055.png",
    viewCount: 0,
  },
  {
    title: "Secret friend",
    src: "secret-friend-141210.mp3",
    thumbnailSrc: "thumbnail_00056.png",
    viewCount: 0,
  },
  {
    title: "Smoke",
    src: "smoke-143172.mp3",
    thumbnailSrc: "thumbnail_00057.png",
    viewCount: 0,
  },
  {
    title: "Spring forest",
    src: "spring-forest-141216.mp3",
    thumbnailSrc: "thumbnail_00058.png",
    viewCount: 0,
  },
  {
    title: "Sunny days indie",
    src: "sunny-days-indie-140928.mp3",
    thumbnailSrc: "thumbnail_00059.png",
    viewCount: 0,
  },
  {
    title: "Tender heart",
    src: "tender-heart-141992.mp3",
    thumbnailSrc: "thumbnail_00060.png",
    viewCount: 0,
  },
  {
    title: "The beat of nature",
    src: "the-beat-of-nature-122841.mp3",
    thumbnailSrc: "thumbnail_00061.png",
    viewCount: 0,
  },
  {
    title: "The upbeat inspiring corporate",
    src: "the-upbeat-inspiring-corporate-141484.mp3",
    thumbnailSrc: "thumbnail_00062.png",
    viewCount: 0,
  },
  {
    title: "Waterfall",
    src: "waterfall-140894.mp3",
    thumbnailSrc: "thumbnail_00063.png",
    viewCount: 0,
  },
  {
    title: "World travel",
    src: "world-travel-142838.mp3",
    thumbnailSrc: "thumbnail_00064.png",
    viewCount: 0,
  },
];
